export const featuredProviders = [
  {
    id: 1,
    name: "Amara Williams",
    title: "Celebrity Hair Stylist",
    location: "Shoreditch, London",
    rating: 4.9,
    reviews: 284,
    price: "£85",
    image: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=500&fit=crop",
    services: ["Haircuts", "Color", "Styling"],
    verified: true,
    featured: true,
  },
  {
    id: 2,
    name: "Sofia Chen",
    title: "Master Makeup Artist",
    location: "Mayfair, London",
    rating: 4.8,
    reviews: 192,
    price: "£120",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=500&fit=crop",
    services: ["Bridal", "Editorial", "Glam"],
    verified: true,
    featured: true,
  },
  {
    id: 3,
    name: "Zara Okonkwo",
    title: "Nail Art Specialist",
    location: "Brixton, London",
    rating: 4.9,
    reviews: 356,
    price: "£45",
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=500&fit=crop",
    services: ["Gel", "Acrylic", "Nail Art"],
    verified: true,
    featured: false,
  },
  {
    id: 4,
    name: "James Mitchell",
    title: "Premium Barber",
    location: "Soho, London",
    rating: 4.7,
    reviews: 421,
    price: "£35",
    image: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=500&fit=crop",
    services: ["Fades", "Beard", "Hot Towel"],
    verified: true,
    featured: false,
  },
  {
    id: 5,
    name: "Luna Reyes",
    title: "Lash & Brow Expert",
    location: "Notting Hill, London",
    rating: 4.8,
    reviews: 167,
    price: "£55",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=500&fit=crop",
    services: ["Extensions", "Lamination", "Tinting"],
    verified: true,
    featured: true,
  },
  {
    id: 6,
    name: "The Gloss House",
    title: "Luxury Salon",
    location: "Kensington, London",
    rating: 4.9,
    reviews: 512,
    price: "£150",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=500&fit=crop",
    services: ["Full Service", "Spa", "Wellness"],
    verified: true,
    featured: true,
  },
];

export const allProviders = [
  ...featuredProviders,
  {
    id: 7,
    name: "Isabella Romano",
    title: "Bridal Specialist",
    location: "Chelsea, London",
    rating: 5.0,
    reviews: 89,
    price: "£200",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=500&fit=crop",
    services: ["Bridal", "Trials", "Party"],
    verified: true,
    featured: false,
  },
  {
    id: 8,
    name: "Marcus Cole",
    title: "Master Barber",
    location: "Hackney, London",
    rating: 4.8,
    reviews: 234,
    price: "£40",
    image: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=500&fit=crop",
    services: ["Skin Fades", "Designs", "Beard"],
    verified: true,
    featured: false,
  },
  {
    id: 9,
    name: "Aisha Patel",
    title: "Skincare Expert",
    location: "Camden, London",
    rating: 4.9,
    reviews: 178,
    price: "£95",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=500&fit=crop",
    services: ["Facials", "Peels", "Micro"],
    verified: true,
    featured: false,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Emily Richardson",
    role: "Fashion Editor",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    rating: 5,
    text: "GlossGo completely changed how I book my beauty appointments. The quality of professionals on here is unmatched. I found my go-to stylist in under 10 minutes.",
  },
  {
    id: 2,
    name: "Marcus Thompson",
    role: "Entrepreneur",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    rating: 5,
    text: "As someone who travels constantly, having a reliable way to book quality barbers in any city is a game-changer. The verification system gives me real confidence.",
  },
  {
    id: 3,
    name: "Priya Sharma",
    role: "Wedding Planner",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    rating: 5,
    text: "I book entire bridal parties through GlossGo. The portfolio feature lets me see exactly what each artist can do. It has saved me countless hours of vetting.",
  },
];

export const howItWorks = [
  {
    step: "01",
    title: "Discover",
    description: "Browse verified beauty professionals near you. Filter by service, style, rating, and availability to find your perfect match.",
    icon: "Search",
  },
  {
    step: "02",
    title: "Book",
    description: "Select your service, choose a time slot, and confirm your appointment in seconds. No phone calls, no waiting.",
    icon: "Calendar",
  },
  {
    step: "03",
    title: "Experience",
    description: "Sit back and enjoy your treatment. Pay securely through the app and leave a review to help the community.",
    icon: "Sparkles",
  },
];

export const serviceCategories = [
  { name: "Hair", icon: "Scissors", count: "2,400+" },
  { name: "Makeup", icon: "Palette", count: "1,800+" },
  { name: "Nails", icon: "Hand", count: "3,200+" },
  { name: "Barber", icon: "User", count: "1,500+" },
  { name: "Lashes", icon: "Eye", count: "900+" },
  { name: "Skincare", icon: "Sparkles", count: "1,100+" },
];

export const stats = [
  { value: "15K+", label: "Verified Professionals" },
  { value: "98%", label: "Satisfaction Rate" },
  { value: "50K+", label: "Monthly Bookings" },
  { value: "4.9", label: "Average Rating" },
];

export const filterOptions = {
  services: ["All Services", "Hair", "Makeup", "Nails", "Barber", "Lashes", "Skincare"],
  price: ["Any Price", "Under £50", "£50 - £100", "£100 - £200", "£200+"],
  rating: ["Any Rating", "4.5+", "4.7+", "4.9+"],
  availability: ["Any Time", "Today", "This Week", "This Weekend"],
};
